- hosts: "servers"
  vars_files:
    - default.config.yml
  
  pre_tasks:
    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes

  tasks:
    - name: Install base packages
      pacman:
        name: 
          - base-devel
          - git 
          - curl
        state: present
      become: yes

    - import_tasks: tasks/setup_dotfiles.yml
    - import_tasks: tasks/setup_shell.yml
    - import_tasks: tasks/install_neovim.yml
